[package]
name = "lym"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.33"
reqwest = "0.11.24"
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
colored = "2.1.0"
